# 文件名: .github/workflows/deploy-to-hf.yml

name: Build and Deploy to Hugging Face Space (v9 - Smart LFS)

on:
  push:
    branches:
      - main # 如果你的主分支是 master，请改成 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 第 1-3 步保持不變
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        run: hugo --minify

      # 第 4 步：使用精細化的 LFS 規則進行部署
      - name: Deploy to HF Space (Smart LFS)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: "hang3976"
          SPACE_NAME: "hao"
        run: |
          # 進入 Hugo 生成的 public 文件夾
          cd public
          
          # 初始化 Git 倉庫並強制創建 main 分支
          git init
          git checkout -b main
          
          # 安裝 Git LFS
          git lfs install
          
          # 【【【 關鍵修正處：精細化 LFS 規則 】】】
          # 創建 .gitattributes 文件，但這次我們指定哪些文件類型走 LFS，哪些不走
          # 只有常見的二進制/大文件類型才使用 LFS
          echo '*.jpg filter=lfs diff=lfs merge=lfs -text' > .gitattributes
          echo '*.jpeg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.png filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.gif filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.webp filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.svg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.mp4 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.pdf filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.zip filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.woff2 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes

          # 告訴 Git，網站的核心文件 *不要* 使用 LFS
          echo '*.html -filter -diff -merge -text' >> .gitattributes
          echo '*.css -filter -diff -merge -text' >> .gitattributes
          echo '*.js -filter -diff -merge -text' >> .gitattributes
          echo '*.xml -filter -diff -merge -text' >> .gitattributes
          echo '*.json -filter -diff -merge -text' >> .gitattributes
          echo '*.txt -filter -diff -merge -text' >> .gitattributes

          # 配置 Git 用戶信息
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          
          # 添加遠程倉庫地址
          HF_SPACE_GIT_URL="https://hf_token:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${SPACE_NAME}"
          git remote add hf_space "${HF_SPACE_GIT_URL}"
          
          # 添加所有文件並提交
          git add .
          git commit -m "Deploy from GitHub Action ${{ github.sha }} with smart LFS"
          
          # 強制推送到 HF Space 的 main 分支
          git push --force hf_space main
