# 文件名: .github/workflows/deploy_huggingface.yml

name: Deploy Website to Hugging Face

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to HF Space (Smart LFS)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: "hang3976"
          SPACE_NAME: "hao"
        run: |
          cd public
          git init
          git checkout -b main
          git lfs install
          echo '*.jpg filter=lfs diff=lfs merge=lfs -text' > .gitattributes
          echo '*.jpeg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.png filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.gif filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.webp filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.svg filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.mp4 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.pdf filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.zip filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.woff2 filter=lfs diff=lfs merge=lfs -text' >> .gitattributes
          echo '*.html -filter -diff -merge -text' >> .gitattributes
          echo '*.css -filter -diff -merge -text' >> .gitattributes
          echo '*.js -filter -diff -merge -text' >> .gitattributes
          echo '*.xml -filter -diff -merge -text' >> .gitattributes
          echo '*.json -filter -diff -merge -text' >> .gitattributes
          echo '*.txt -filter -diff -merge -text' >> .gitattributes
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          HF_SPACE_GIT_URL="https://hf_token:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${SPACE_NAME}"
          git remote add hf_space "${HF_SPACE_GIT_URL}"
          git add .
          git commit -m "Deploy from GitHub Action ${{ github.sha }} with smart LFS"
          git push --force hf_space main
